from edgar import Company, set_identity
from edgar.xbrl import XBRLS
import pandas as pd
from . import config
from rich.console import Console

console = Console()


def _init_identity():
    set_identity(config.EDGAR_IDENTITY)


def _get_company(ticker):
    _init_identity()
    return Company(ticker)


def get_financials(ticker):
    company = _get_company(ticker)
    return company.get_financials()


def get_multi_period_statements(ticker, form="10-K", periods=4):
    company = _get_company(ticker)
    filings = company.get_filings(form=form).filter(amendments=False).head(periods)
    if len(filings) == 0:
        return None
    xbrls = XBRLS.from_filings(filings)
    return xbrls


def get_income_statement(ticker, periods=4):
    company = _get_company(ticker)
    stmt = company.income_statement(periods=periods)
    if stmt is None:
        return None
    return stmt.to_dataframe()


def get_balance_sheet(ticker, periods=4):
    company = _get_company(ticker)
    stmt = company.balance_sheet(periods=periods)
    if stmt is None:
        return None
    return stmt.to_dataframe()


def get_cashflow_statement(ticker, periods=4):
    company = _get_company(ticker)
    stmt = company.cashflow_statement(periods=periods)
    if stmt is None:
        return None
    return stmt.to_dataframe()


def get_key_metrics(ticker):
    company = _get_company(ticker)
    financials = company.get_financials()
    if financials is None:
        return {}

    metrics = {}
    try:
        metrics["revenue"] = financials.get_revenue()
    except Exception:
        pass
    try:
        metrics["net_income"] = financials.get_net_income()
    except Exception:
        pass
    try:
        metrics["operating_income"] = financials.get_operating_income()
    except Exception:
        pass
    try:
        metrics["total_assets"] = financials.get_total_assets()
    except Exception:
        pass
    try:
        metrics["total_liabilities"] = financials.get_total_liabilities()
    except Exception:
        pass
    try:
        metrics["stockholders_equity"] = financials.get_stockholders_equity()
    except Exception:
        pass
    try:
        ocf = financials.get_operating_cash_flow()
        if ocf is None:
            # Fallback: extract from cash flow statement DataFrame
            cf_df = financials.cashflow_statement().to_dataframe()
            cf_indexed = cf_df.set_index("label") if "label" in cf_df.columns else cf_df
            for label in ["Cash generated by operating activities", "Net cash from operating activities"]:
                if label in cf_indexed.index:
                    row = cf_indexed.loc[label]
                    period_col = [c for c in row.index if c.startswith("FY") or c.startswith("20")]
                    if period_col:
                        val = row[period_col[0]]
                        if pd.notna(val):
                            ocf = float(val)
                            break
        metrics["operating_cash_flow"] = ocf
    except Exception:
        pass
    try:
        fcf = financials.get_free_cash_flow()
        if fcf is None:
            # Fallback: compute OCF - CapEx
            ocf_val = metrics.get("operating_cash_flow")
            capex = financials.get_capital_expenditures()
            if ocf_val and capex:
                fcf = ocf_val - abs(capex)
        metrics["free_cash_flow"] = fcf
    except Exception:
        pass
    try:
        metrics["current_assets"] = financials.get_current_assets()
    except Exception:
        pass
    try:
        metrics["current_liabilities"] = financials.get_current_liabilities()
    except Exception:
        pass

    if metrics.get("revenue") and metrics.get("net_income"):
        metrics["net_margin"] = metrics["net_income"] / metrics["revenue"]
    if metrics.get("revenue") and metrics.get("operating_income"):
        metrics["operating_margin"] = metrics["operating_income"] / metrics["revenue"]
    if metrics.get("current_assets") and metrics.get("current_liabilities") and metrics["current_liabilities"] > 0:
        metrics["current_ratio"] = metrics["current_assets"] / metrics["current_liabilities"]
    if metrics.get("total_liabilities") and metrics.get("stockholders_equity") and metrics["stockholders_equity"] > 0:
        metrics["debt_to_equity"] = metrics["total_liabilities"] / metrics["stockholders_equity"]
    if metrics.get("net_income") and metrics.get("stockholders_equity") and metrics["stockholders_equity"] > 0:
        metrics["roe"] = metrics["net_income"] / metrics["stockholders_equity"]

    return metrics


def compute_yoy_changes(ticker):
    company = _get_company(ticker)
    stmt = company.income_statement(periods=4)
    if stmt is None:
        return None

    df = stmt.to_dataframe()
    period_cols = [c for c in df.columns if c.startswith("FY") or c.startswith("20")]
    if len(period_cols) < 2:
        return None

    # The DataFrame is already indexed by concept from the statement
    changes = {}

    key_concepts = [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "Revenue",
        "GrossProfit",
        "OperatingIncomeLoss",
        "NetIncomeLoss",
        "NetIncome",
        "CostOfGoodsAndServicesSold",
        "OperatingExpenses",
    ]

    # Build a mapping from concept to label for display names
    label_map = {}
    if "label" in df.columns:
        for concept_name in df.index:
            label_map[concept_name] = df.loc[concept_name, "label"] if concept_name in df.index else concept_name

    for concept in key_concepts:
        if concept in df.index:
            row = df.loc[concept]
            values = [(c, row[c]) for c in period_cols if pd.notna(row.get(c))]
            if len(values) >= 2:
                latest = values[0][1]
                prior = values[1][1]
                if prior and prior != 0:
                    pct = ((latest - prior) / abs(prior)) * 100
                    display_name = label_map.get(concept, concept)
                    changes[display_name] = {
                        "latest_period": values[0][0],
                        "latest_value": float(latest),
                        "prior_period": values[1][0],
                        "prior_value": float(prior),
                        "yoy_change_pct": round(pct, 2),
                    }
    return changes


def get_financial_summary_as_markdown(ticker):
    company = _get_company(ticker)
    financials = company.get_financials()
    if financials is None:
        return None

    parts = []
    parts.append(f"# {ticker} Financial Summary\n")

    try:
        income = financials.income_statement()
        parts.append("## Income Statement")
        parts.append(income.to_markdown())
    except Exception:
        pass

    try:
        balance = financials.balance_sheet()
        parts.append("\n## Balance Sheet")
        parts.append(balance.to_markdown())
    except Exception:
        pass

    try:
        cashflow = financials.cashflow_statement()
        parts.append("\n## Cash Flow Statement")
        parts.append(cashflow.to_markdown())
    except Exception:
        pass

    return "\n".join(parts)


def get_notes_as_markdown(ticker, focus=None):
    company = _get_company(ticker)
    tenk = company.get_filings(form="10-K").latest().obj()
    if tenk is None:
        return None

    parts = []
    try:
        notes = tenk.notes
        if notes:
            if focus:
                md = notes.to_markdown(focus=focus)
            else:
                md = notes.to_markdown()
            parts.append(md)
    except Exception:
        pass

    return "\n".join(parts) if parts else None


def get_filing_sections(ticker, sections=None):
    company = _get_company(ticker)
    tenk = company.get_filings(form="10-K").latest().obj()
    if tenk is None:
        return {}

    results = {}
    if sections is None:
        sections = ["Item 1", "Item 1A", "Item 7"]

    for section_name in sections:
        try:
            report = tenk.get_report(section_name)
            if report:
                results[section_name] = report.text[:3000] if hasattr(report, "text") else str(report)[:3000]
        except Exception:
            try:
                item = tenk[section_name]
                if item:
                    results[section_name] = str(item)[:3000]
            except Exception:
                pass

    return results


def get_quarterly_comparison(ticker):
    company = _get_company(ticker)
    try:
        quarterly = company.get_quarterly_financials()
        income = quarterly.income_statement()
        if income is None:
            return None
        return income.to_dataframe()
    except Exception:
        return None


def get_filing_metadata(ticker, form_type="10-Q", count=5):
    """Get filing metadata: dates, accession numbers, periods."""
    company = _get_company(ticker)
    filings = company.get_filings(form=form_type).filter(amendments=False).head(count)
    if len(filings) == 0:
        return []

    results = []
    for f in filings:
        meta = {
            "form": f.form,
            "filing_date": str(f.filing_date),
            "period_of_report": str(f.period_of_report) if hasattr(f, "period_of_report") else None,
            "accession_no": f.accession_no,
            "company": f.company,
        }
        results.append(meta)
    return results


def get_latest_filing_date(ticker, form_type="10-Q"):
    """Get just the most recent filing date for a form type."""
    meta = get_filing_metadata(ticker, form_type, count=1)
    if meta:
        return meta[0]
    return None


def search_xbrl_facts(ticker, query_text, form_type=None, periods_back=3):
    """Search for XBRL facts by concept query. Returns matching facts from DataFrame."""
    company = _get_company(ticker)

    if form_type:
        filings_obj = company.get_filings(form=form_type)
        filing = filings_obj.filter(amendments=False).latest()
        if filing is None:
            return []
        return _extract_facts_from_filing(filing, query_text, form_type)

    results = []
    forms_to_try = ["10-K", "10-Q"]
    for form in forms_to_try:
        try:
            filings_obj = company.get_filings(form=form)
            recent = filings_obj.filter(amendments=False).head(periods_back)
            for f in recent:
                found = _extract_facts_from_filing(f, query_text, form)
                results.extend(found)
        except Exception:
            continue

    return results


# Maps user-friendly query text to XBRL concept substrings to search for
CONCEPT_ALIASES = {
    "effective tax rate": ["incometaxexpensebenefit", "incomelossfromcontinuingoperationsbeforeincometaxes"],
    "tax rate": ["incometaxexpensebenefit", "incomelossfromcontinuingoperationsbeforeincometaxes"],
    "research and development expense": ["researchanddevelopmentexpense"],
    "research and development": ["researchanddevelopmentexpense"],
    "r&d expense": ["researchanddevelopmentexpense"],
    "depreciation": ["depreciationdepletionandamortization"],
    "depreciation and amortization": ["depreciationdepletionandamortization"],
    "interest expense": ["interestexpense", "interest成本"],
    "interest income": ["interestincome"],
    "stock-based compensation": ["allocatedsharebasedcompensationexpense"],
    "share-based compensation": ["allocatedsharebasedcompensationexpense"],
    "stock compensation": ["allocatedsharebasedcompensationexpense"],
    "dividends per share": ["dividendspershare", "commonstockdividends"],
    "dividend per share": ["dividendspershare", "commonstockdividends"],
    "shares outstanding": ["commonstocksharesoutstanding", "entitycommonstocksharesoutstanding"],
    "diluted shares outstanding": ["dilutedsharesoutstanding"],
    "goodwill": ["goodwill"],
    "intangible assets": ["intangibleassetsnetexcludinggoodwill", "intangibleassets"],
    "share repurchases": ["repurchaseofcommonstock", "stockrepurchased"],
    "buyback": ["repurchaseofcommonstock", "stockrepurchased"],
    "cost of revenue": ["costofrevenue", "costofgoodssold"],
    "cost of goods sold": ["costofgoodssold", "costofrevenue"],
    "operating expenses": ["operatingexpenses"],
    "earnings per share": ["earningspershare"],
    "diluted earnings per share": ["dilutedearningspershare"],
    "basic earnings per share": ["basicearningspershare"],
    "working capital": ["workingcapital"],
}


def _extract_facts_from_filing(filing, query_text, form_type):
    """Extract matching facts from a single filing using DataFrame."""
    results = []
    try:
        xbrl = filing.xbrl()
        if xbrl is None:
            return results
        df = xbrl.facts.to_dataframe()
        filing_date = str(filing.filing_date)
        period = str(filing.period_of_report) if hasattr(filing, "period_of_report") else filing_date

        query_lower = query_text.lower()

        # Get concept substrings to search for
        search_terms = CONCEPT_ALIASES.get(query_lower, [query_lower.replace(" ", "")])

        for term in search_terms:
            matches = df[df["concept"].str.lower().str.contains(term, na=False)]
            # Filter to non-dimensioned rows (consolidated figures)
            if "is_dimensioned" in matches.columns:
                consolidated = matches[matches["is_dimensioned"] == False]
                if len(consolidated) > 0:
                    matches = consolidated

            # Keep only the most recent quarterly view (duration periods, not YTD)
            if "period_key" in matches.columns and len(matches) > 0:
                duration_rows = matches[matches["period_key"].str.startswith("duration", na=False)]
                if len(duration_rows) > 0:
                    matches = duration_rows

            # Deduplicate by concept, keeping the first (most recent) occurrence
            seen_concepts = set()
            for _, row in matches.iterrows():
                concept = str(row.get("concept", ""))
                if concept in seen_concepts:
                    continue
                seen_concepts.add(concept)
                value = row.get("numeric_value", row.get("value"))
                unit = str(row.get("unit_ref", row.get("currency", "")))
                label = str(row.get("label", row.get("original_label", concept)))

                # Convert to float if possible
                try:
                    value = float(value) if value is not None else None
                except (ValueError, TypeError):
                    value = row.get("value")

                dedup_key = f"{concept}_{value}_{period}"
                results.append({
                    "concept": concept,
                    "label": label,
                    "value": value,
                    "unit": unit,
                    "period": period,
                    "filing_date": filing_date,
                    "form_type": form_type,
                })
    except Exception as e:
        console.print(f"[dim]Error extracting XBRL facts: {e}[/dim]")

    # For "effective tax rate", compute it from tax expense / pre-tax income
    if query_lower in ("effective tax rate", "tax rate"):
        results = _compute_effective_tax_rate(df, filing_date, period, form_type, results)

    return results


def _compute_effective_tax_rate(df, filing_date, period, form_type, existing_results):
    """Compute effective tax rate from XBRL facts if raw concepts found."""
    try:
        tax_expense_rows = df[df["concept"].str.lower().str.contains("incometaxexpensebenefit", na=False)]
        pretax_income_rows = df[df["concept"].str.lower().str.contains("incomelossfromcontinuingoperationsbeforeincometaxes", na=False)]

        if "is_dimensioned" in tax_expense_rows.columns:
            tax_expense_rows = tax_expense_rows[tax_expense_rows["is_dimensioned"] == False]
            pretax_income_rows = pretax_income_rows[pretax_income_rows["is_dimensioned"] == False]

        if len(tax_expense_rows) == 0 or len(pretax_income_rows) == 0:
            return existing_results

        # Use the first (most recent) non-dimensioned values with valid numbers
        for _, trow in tax_expense_rows.iterrows():
            try:
                tax_val = float(trow.get("numeric_value", 0))
                if tax_val == 0 or tax_val != tax_val:  # skip zero or NaN
                    continue
                # Find matching pretax row
                for _, prow in pretax_income_rows.iterrows():
                    try:
                        pretax_val = float(prow.get("numeric_value", 0))
                        if pretax_val == 0 or pretax_val != pretax_val:  # skip zero or NaN
                            continue
                        effective_rate = tax_val / pretax_val
                        return [{
                            "concept": "us-gaap:EffectiveIncomeTaxRate (computed)",
                            "label": "Effective Income Tax Rate",
                            "value": effective_rate,
                            "unit": "percent",
                            "period": period,
                            "filing_date": filing_date,
                            "form_type": form_type,
                        }]
                    except (ValueError, TypeError):
                        continue
            except (ValueError, TypeError):
                continue
    except Exception:
        pass

    return existing_results


def get_company_facts_list(ticker, form_type="10-Q"):
    """Get the full list of available XBRL concepts for a company's latest filing."""
    company = _get_company(ticker)
    filings_obj = company.get_filings(form=form_type)
    filing = filings_obj.filter(amendments=False).latest()
    if filing is None:
        return []
    xbrl = filing.xbrl()
    if xbrl is None:
        return []
    df = xbrl.facts.to_dataframe()
    return df["concept"].unique().tolist()
